# Generated by Django 4.1.7 on 2023-03-10 12:07

import django.core.validators
from django.db import migrations, models
import transcription.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafield',
            name='upload_file',
            field=models.FileField(upload_to=transcription.models.unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
        ),
    ]
