# Generated by Django 4.1.7 on 2023-03-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_alter_mediafield_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafield',
            name='upload_file',
        ),
    ]
