# Generated by Django 4.1.7 on 2023-04-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_remove_mediafield_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafield',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='mediafield',
            name='language_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
